name: docs 

on:
  push:
    branches:
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Installs Python and other requirements
      - name: Prepare environment
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install -r requirements.txt

      # Builds the static site
      - name: Build docs
      - run: mkdocs build

      # Deploys to the GitHub pages branch
      - name: Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./site